CREATE TABLE apismgr.INVENTORY_INVENTORY
(
    INVENTORY_ID           VARCHAR2(36) NOT NULL,
    NAME                   VARCHAR2(256),
    DESCRIPTION            CLOB,
    TYPE                   VARCHAR2(256),
    OTHER_TYPE             CLOB,
    CREATED_AT             DATE NOT NULL,
    UPDATED_AT             DATE,
    DELETED_AT             DATE,
    CONSTRAINT PK_INVENTORY_INVENTORY PRIMARY KEY
    (
        INVENTORY_ID
    )
    USING INDEX TABLESPACE INDX)
    TABLESPACE DATA
/

CREATE PUBLIC SYNONYM INVENTORY_INVENTORY FOR apismgr.INVENTORY_INVENTORY;

COMMENT ON TABLE apismgr.INVENTORY_INVENTORY IS 'Contains records of data integrations that serve data to other entities.';
COMMENT ON COLUMN apismgr.INVENTORY_INVENTORY.INVENTORY_ID IS 'Primary key. 128 bit UUID. Able to be generated by client.';
COMMENT ON COLUMN apismgr.INVENTORY_INVENTORY.NAME IS 'Name of API or Talend job.';
COMMENT ON COLUMN apismgr.INVENTORY_INVENTORY.DESCRIPTION IS 'Short description of API or Talend job.';
COMMENT ON COLUMN apismgr.INVENTORY_INVENTORY.TYPE IS 'Type of mechanism being used to deliver the data. Possible values are API, Talend, or Other.';
COMMENT ON COLUMN apismgr.INVENTORY_INVENTORY.OTHER_TYPE IS 'Explanation if TYPE field is Other.';
COMMENT ON COLUMN apismgr.INVENTORY_INVENTORY.CREATED_AT IS 'Stores SYSDATE when inventory was created.';
COMMENT ON COLUMN apismgr.INVENTORY_INVENTORY.UPDATED_AT IS 'Stores SYSDATE when inventory was updated.';
COMMENT ON COLUMN apismgr.INVENTORY_INVENTORY.DELETED_AT IS 'Stores SYSDATE when inventory was deleted.';

CREATE TABLE apismgr.INVENTORY_FIELDS
(
    FIELD_ID               NUMBER NOT NULL,
    CLIENT_FIELD_ID        VARCHAR2(36) NOT NULL,
    PARENT_ID              VARCHAR2(36) NOT NULL,
    INVENTORY_ID           VARCHAR2(36) NOT NULL,
    FIELD                  VARCHAR2(256),
    DESCRIPTION            CLOB,
    TYPE                   VARCHAR2(256) NOT NULL,
    CREATED_AT             DATE NOT NULL,
    UPDATED_AT             DATE,
    DELETED_AT             DATE,
    CONSTRAINT PK_INVENTORY_FIELDS PRIMARY KEY
        (
            FIELD_ID 
        )
    USING INDEX TABLESPACE INDX)
    TABLESPACE DATA  
/

CREATE PUBLIC SYNONYM INVENTORY_FIELDS FOR apismgr.INVENTORY_FIELDS;

COMMENT ON TABLE apismgr.INVENTORY_FIELDS IS 'Contains fields given to entities, or fields used as API query parameters';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.FIELD_ID IS 'Primary key. For internal use only. Not seen by client.';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.CLIENT_FIELD_ID IS 'Able to be generated and seen by client.';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.PARENT_ID IS 'ID of parent object.';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.INVENTORY_ID IS 'ID of top level inventory object';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.FIELD IS 'Name of field.';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.DESCRIPTION is 'Description of field.';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.TYPE is 'Whether field is provided data or used as an API query parameter.';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.CREATED_AT is 'Stores SYSDATE when field record was created.';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.UPDATED_AT is 'Stores SYSDATE when field record was updated.';
COMMENT ON COLUMN apismgr.INVENTORY_FIELDS.DELETED_AT is 'Stores SYSDATE when field record was deleted.';

CREATE TABLE apismgr.INVENTORY_CONSUMING_ENTITIES
(
    ENTITY_ID              NUMBER NOT NULL,
    CLIENT_ENTITY_ID       VARCHAR2(36) NOT NULL,
    INVENTORY_ID           VARCHAR2(36) NOT NULL,
    ENTITY_NAME            VARCHAR2(256),
    APPLICATION_NAME       VARCHAR2(256),
    ENTITY_CONTACT_NAME    VARCHAR2(256),
    ENTITY_EMAIL           VARCHAR2(256),
    ENTITY_PHONE           VARCHAR2(20),
    ENTITY_URL             VARCHAR2(1024),
    INTERNAL               VARCHAR2(1) NOT NULL,
    MOU                    VARCHAR2(1024),
    CREATED_AT             DATE NOT NULL,
    UPDATED_AT             DATE,
    DELETED_AT             DATE,
    CONSTRAINT PK_INVENTORY_CONSUMERS PRIMARY KEY
        (
            ENTITY_ID
        )    
    USING INDEX TABLESPACE INDX)
    TABLESPACE DATA  
/

CREATE PUBLIC SYNONYM INVENTORY_CONSUMING_ENTITIES FOR apismgr.INVENTORY_CONSUMING_ENTITIES;

COMMENT ON TABLE apismgr.INVENTORY_CONSUMING_ENTITIES IS 'Contains entities (OSU departments or outside vendors) that consume the data given by an API or Talend job.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.ENTITY_ID IS 'Primary key. For internal use only. Not seen by client.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.CLIENT_ENTITY_ID IS 'Able to be generated and seen by client.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.INVENTORY_ID IS 'Foreign key for INVENTORY table.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.ENTITY_NAME IS 'Department or vendor name.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.APPLICATION_NAME IS 'Name of application being used or maintained by the entity which consumes the data provided to them.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.ENTITY_CONTACT_NAME IS 'Contact name of person or group on behalf of the entity.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.ENTITY_EMAIL IS 'Email address of entity.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.ENTITY_PHONE IS 'Phone number of entity.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.ENTITY_URL IS 'Website of entity.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.INTERNAL IS 'If false, the entity is a third-party vendor governed outside the scope of the university.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.MOU IS 'URL of memorandum of understanding document.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.CREATED_AT IS 'Stores SYSDATE when entity record was created.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.UPDATED_AT IS 'Stores SYSDATE when entity record was updated.';
COMMENT ON COLUMN apismgr.INVENTORY_CONSUMING_ENTITIES.DELETED_AT IS 'Stores SYSDATE when entity record was deleted.';

CREATE TABLE apismgr.INVENTORY_PROVIDED_DATA
(
    DATA_ID                NUMBER NOT NULL,
    CLIENT_DATA_ID         VARCHAR2(36) NOT NULL,
    INVENTORY_ID           VARCHAR2(36) NOT NULL,
    SOURCE                 VARCHAR2(256),
    SOURCE_DESCRIPTION     CLOB,
    SOURCE_TYPE            VARCHAR2(256),
    OTHER_SOURCE_TYPE      CLOB,
    API_URL                VARCHAR2(1024),
    INTERNAL               VARCHAR2(1),
    CREATED_AT             DATE NOT NULL,
    UPDATED_AT             DATE,
    DELETED_AT             DATE,
    CONSTRAINT PK_INVENTORY_PROVIDED_DATA PRIMARY KEY
        (
            DATA_ID
        )
    USING INDEX TABLESPACE INDX)
    TABLESPACE DATA  
/

CREATE PUBLIC SYNONYM INVENTORY_PROVIDED_DATA FOR apismgr.INVENTORY_PROVIDED_DATA;

COMMENT ON TABLE apismgr.INVENTORY_PROVIDED_DATA IS 'Contains data provided to by the API or Talend job.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.DATA_ID IS 'Primary key. For internal use only. Not seen by client.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.CLIENT_DATA_ID IS 'Able to be generated and seen by client.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.INVENTORY_ID IS 'Foreign key for INVENTORY table.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.SOURCE IS 'Short description of the data source.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.SOURCE_DESCRIPTION IS 'Long description of the data source.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.SOURCE_TYPE IS 'Type of data source being accessed directly. Possible values are API, Database, or Other.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.OTHER_SOURCE_TYPE IS 'Explanation if SOURCE_TYPE is Other.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.API_URL IS 'URL of API being called, if SOURCE_TYPE is API.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.INTERNAL IS 'If false, the data source is hosted and maintained outside of the university.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.CREATED_AT IS 'Stores SYSDATE when provided data record was created.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.UPDATED_AT IS 'Stores SYSDATE when provided data record was created.';
COMMENT ON COLUMN apismgr.INVENTORY_PROVIDED_DATA.DELETED_AT IS 'Stores SYSDATE when provided data record was deleted.';

CREATE SEQUENCE apismgr.INVENTORY_FIELDS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE PUBLIC SYNONYM INVENTORY_FIELDS_SEQ FOR apismgr.INVENTORY_FIELDS_SEQ;

CREATE SEQUENCE apismgr.INVENTORY_CONSUMERS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE PUBLIC SYNONYM INVENTORY_CONSUMERS_SEQ FOR apismgr.INVENTORY_CONSUMERS_SEQ;

CREATE SEQUENCE apismgr.INVENTORY_PROVIDED_DATA_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE PUBLIC SYNONYM INVENTORY_PROVIDED_DATA_SEQ FOR apismgr.INVENTORY_PROVIDED_DATA_SEQ;